# https://docs.lagoon.sh/using-lagoon-the-basics/lagoon-yml/
docker-compose-yaml: docker-compose.yml

project: demo-vagov-cmstest

tasks:
  post-rollout:
#    - run:
#        name: Run drush deploy
#        command: drush deploy
#        service: cli
#        shell: bash
