# https://docs.lagoon.sh/using-lagoon-the-basics/lagoon-yml/
docker-compose-yaml: docker-compose.yml

project: demo-vagov-cmstest

tasks:
  # pre-rollout tasks run on the old containers
  pre-rollout:

  # post-rollout tasks run on the new containers
  post-rollout:
    - run:
        name: NPM install
        command: /app/bin/npm install 
        service: cli
        shell: bash
    - run:
        name: Install VA Themes
        command: composer va:theme:compile
        service: cli
        shell: bash
    - run:
        name: Install VA web 
        command: composer va:web:install
        service: cli
        shell: bash

