name: "VA.gov CMS Documentation Only PR Check"
description: "Checks if the current PR contains only documentation changes"
inputs: {}
outputs:
  docs-only:
    description: "'true' if the PR contains only documentation changes, otherwise 'false'"
    value: ${{ steps.docs-only.outputs.result }}

runs:
  using: "composite"
  steps:

    - name: Check for documentation only changes
      id: docs-only
      uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
      with:
        script: |
          const opts = github.rest.pulls.listFiles.endpoint.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          })
          const files = await github.paginate(opts, (response) =>
            response.data.map((file) => file.filename))

          for (const file of files) {
            console.log(`Checking PR file: ${file}`)
            if (!file.endsWith('.md')) {
              return "false"
            }
          }

          return "true"
        result-encoding: string
