
name: "Taxonomy - Add Term"
description: "Use this template when adding terms to the Service or Benefit taxonomy."
title: "[ADD] (Term name) to (taxonomy name)"
labels: Content, Content governance

body:

- type: textarea
  id: which-taxonomy
  attributes:
    label:  Which Taxonomy is this term for?
    value:
      - VA Benefits taxonomy
      - VA services taxonomy
      - Other
  validations:
    required: true
- type: input
  id: term-name
  attributes:
    label: Proposed term name/label
    description: e.g. Veterans Pension
  validations:
    required: true
- type: input
  id: machine-name
  attributes:
    label: Proposed machine name/ API ID
    description: va_service_veterans_pension
  validations:
    required: false 
- type: dropdown
  id: overlap
  attributes:
    label: Does this overlap with any existing term in the taxonomy?
    multiple: false
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true
- type: textarea
  id: rationale
  attributes:
    label: Rationale for adding this term
    description: Write a short explanation of why this term is needed. Include links to any relevant issues, research findings, etc.
  validations:
    required: true 
- type: dropdown
  id: products
  attributes:
    label: Which products will this term impact?
    multiple: true
    options:
      - VAMCs
      - Vet Centers
      - VBA Regional Office
      - Benefit hubs
      - Other
  validations:
      required: false 
- type: dropdown
  id: stakeholders
  attributes:
    label: Have stakeholders from impacted products been consulted?
    multiple: false
    options:
        - 'Yes'
        - 'No'
  validations:
    required: true  
- type: dropdown
  id: subfields
  attributes:
    label: Have you drafted content for all the relevant subfields?
    multiple: false
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true   
- type: textarea
  id: extra
  attributes:
    label: Additional notes
    description: 
  validations:
    required: false

