dist: trusty
language: php

cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 7.0

env:
  - VERSION=HEAD
  - VERSION=1.4.0-beta2
  - VERSION=1.2.0-alpha2

addons:
  chrome: stable

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - google-chrome-stable --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  - export SIMPLETEST_DB=sqlite://localhost/db.sqlite

  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build the Lightning code base.
  - composer install

  # Install Acquia Publish cleanly so that settings.php will be created properly.
  - lightning install 'sqlite\://db.sqlite' headless_lightning 'http://127.0.0.1:8080'
  # Import the fixture and update from it, if it exists.
  - lightning update $VERSION
  - drush cache:rebuild
  - drush config:set moderation_dashboard.settings redirect_on_login 1 --yes

before_script:
  - cd $TRAVIS_BUILD_DIR/docroot
  - drush runserver --default-server=builtin 8080 &>/dev/null &

script:
  - composer validate ../composer.json --no-check-all --ansi --no-interaction
  - phpunit --configuration ./core --group headless
  - cd ..
  - behat --strict --config .behat.yml --tags=headless

matrix:
  fast_finish: true
