name: Delete Tugboat Preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths-ignore:
      - '**.md'

jobs:
  gha_diagnostics:
    runs-on: ubuntu-latest
    name: Diagnose github context
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"