name: "Repair PR Title"

on:
  pull_request:
    types: [opened, edited]

jobs:
  repair_pr_title:
    runs-on: ubuntu-latest

    steps:

    - name: Update PR title
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        UPDATED_TITLE="$(echo "$PR_TITLE" | sed -E 's/vacms ([0-9]+) /VACMS-\1: /I')"
        if [ "$PR_TITLE" != "$UPDATED_TITLE" ]; then
          ESCAPED_TITLE=$(jq -R --slurp <<< "$UPDATED_TITLE")
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.pull_request.url }}" \
            -d "{\"title\":$ESCAPED_TITLE}"
        fi
      shell: bash
