name: "Repair PR Title"

on:
  pull_request:
    types: [opened, edited]

jobs:
  repair_pr_title:
    runs-on: ubuntu-latest

    steps:

    - name: Update PR title
      run: |
        UPDATED_TITLE=$(jq -R --slurp <<< "${{ github.event.pull_request.title }}" | sed -E 's/vacms ([0-9]+) /VACMS-\1: /I')
        if [ "${{ github.event.pull_request.title }}" != "$UPDATED_TITLE" ]; then
          ESCAPED_TITLE=$(jq -R --slurp <<< "$UPDATED_TITLE")
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -d "{\"title\":$ESCAPED_TITLE}"
        fi
      shell: bash
