name: "Repair PR Title"

on:
  pull_request:
    types: [opened, edited]

jobs:
  repair_pr_title:
    runs-on: ubuntu-latest

    steps:

    - name: Update PR title
      run: |
        PR_TITLE=${{ github.event.pull_request.title }}
        UPDATED_TITLE=$(echo "$PR_TITLE" | sed -E 's/vacms ([0-9]+) /VACMS-\1: /I')
        if [ "$PR_TITLE" != "$UPDATED_TITLE" ]; then
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            -d '{"title":"'"$UPDATED_TITLE"'"}'
        fi
      shell: bash
