name: CMS-Test Runtime Tasks

on:
  workflow_dispatch:
jobs:
  login-ecr:
    runs-on:
      - self-hosted
      - linux
      - x64    
    steps:
    - name: Login to Amazon ECR
      id: login-ecr
      run: aws ecr get-login-password --region us-gov-west-1 | docker login --username AWS --password-stdin 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com

  runtime-task:
    runs-on:
      - self-hosted
      - linux
      - x64
    needs: login-ecr
    container:
      image: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/cms-ansible:latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-gov-west-1
        role-to-assume: ${{ secrets.AWS_VAGOV_CMS_PROD_ECR_POWERUSER_ROLE }}
        role-duration-seconds: 900
        role-session-name: vsp-vagov-cms-githubaction          
        
    - name: Get bot token from Parameter Store
      uses: marvinpinto/action-inject-ssm-secrets@latest
      with:
        ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
        env_variable_name: VA_VSP_BOT_GITHUB_TOKEN    
        
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: department-of-veterans-affairs/vsp-infra-cms
        token: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}      
      
    - name: List inventory
      working-directory: ansible/
      run: ansible-inventory -i inventory/aws_ec2.yml --graph
