name: CMS-Test Runtime Tasks

on:
  workflow_dispatch:
jobs:
  login-ecr:
    runs-on:
      - self-hosted
      - linux
      - x64    
    steps:
   
    # Instead of using a combination aws-actions configure-aws-credential and amazon-ecr-login to login in to 
    # Amazon ECR use this aws cli command that pipes to docker. AWS CLI will automatically use the instance profile
    # credentials to obtain the login password. Docker CLI will automatically store the password in the runner'socker config.json
    # The aws-actions commands will not do this without additional steps.
    - name: Login to Amazon ECR
      id: login-ecr
      run: aws ecr get-login-password --region us-gov-west-1 | docker login --username AWS --password-stdin 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com

  runtime-task:
    runs-on:
      - self-hosted
      - linux
      - x64
    needs: login-ecr
    container:
      image: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/cms-ansible:latest
    steps:

    - name: Get AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-gov-west-1        
        
    - name: Get bot token from Parameter Store
      uses: marvinpinto/action-inject-ssm-secrets@latest
      with:
        ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
        env_variable_name: VA_VSP_BOT_GITHUB_TOKEN    

    - name: Get bot token from Parameter Store
      uses: marvinpinto/action-inject-ssm-secrets@latest
      with:
        ssm_parameter: /cms/ansible_ssh_id_rsa
        env_variable_name: ANSIBLE_SSH_ID_RSA

    - name: mkdir .ssh
      run: mkdir -p ~/.ssh
      
    - name: setup ssh config
      run: |
        echo -e "Host *
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
        " >> ~/.ssh/config
        
    - name: setup ssh private key
      run: |
        echo -e "${{ env.ANSIBLE_SSH_ID_RSA }}" >> ~/.ssh/id_rsa
        chmod 0600 ~/.ssh/*

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: department-of-veterans-affairs/vsp-infra-cms
        token: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}

    - name: Run Test Playbook
      working-directory: ansible/
      run: ansible-playbook --verbose --extra-vars "deployment_name=cms-test deployment_env=vagov_staging" cms/test.yml
