name: CMS-Test Runtime Tasks
on:
  workflow_dispatch:
jobs:
  login-ecr:
    runs-on:
      - self-hosted
      - linux
      - x64    
    steps:
    - name: Login to Amazon ECR
      id: login-ecr
      run: aws ecr get-login-password --region us-gov-west-1 | docker login --username AWS --password-stdin 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com

  runtime-task:
    runs-on:
      - self-hosted
      - linux
      - x64
    needs: login-ecr
    container:
      image: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/cms-ansible:latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: department-of-veterans-affairs/vsp-infra-cms
    - name: Check Version
      run: ansible --version
    - name: Check galaxy list
      run: ansible-galaxy collection list
    - name: find cfg
      run: find / -type f -name ansible.cfg
    - name: List inventory
      run: ansible-inventory --graph
